[build]
  functions = "netlify/functions"  # Points to the directory containing your functions
  publish = "."                    # Points to the directory to publish (root in this case)

[dev]
  command = "npm start"            # Command to start your dev server (if using one)
  publish = "."  